# docs/swagger.yaml

#
swagger: '2.0'
info:
    title: alloEscrow
    version: 1.0.0
    description: A sample Api for demo
host: localhost:3000/
basePath: /api/v1/
schemes:
    - http
paths:
    /users:
        get:
            summary: Get all users
            responses:
                200:
                    description: Successful responses
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/User'
        post:
            summary: Create a New User
            parameters:
                -in : body
                name: users
                description: User Object to be created
                required:true
                schema:
                    $ref: '#/definitions/User'
            responses:
                201
                   description: User created successfully
definitions:
    User:
        type: object
        properties:
            id:
                type: integer
                format: int64
            name:
                type: string
            email:
                type:string
                format: email